config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  
  root 'pages#index'
  
  resources :links, only: [:show, :new, :create]

end

app/models/link.rb
class Link < ActiveRecord::Base
   belongs_to :user 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :links
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
    # User must be signed in before continuing
    before_action :authenticate_user!, except: [:show]
    
    def show
        @link = Link.find(params[:id])
    end
    
    def new
        @link = Link.new
    end
    
    def create
        # Strong parameters restricts input
        @link = Link.new(link_params)
        if @link.save
            redirect_to root_path
        end
    end
    
    private
    
    def link_params
        params.require(:link).permit(:url, :title).merge(user_id: current_user.id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    # index, show, create, new, update (method names)
    def index
        @links = Link.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
    <% if current_user.present? %>
      <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
    <% else %>
      <%= link_to 'Sign In', new_user_session_path %>
      <%= link_to 'Register', new_user_registration_path %>
    <% end %>
  
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
<%= yield %>
</body>
</html>

app/views/links/new.html.erb
<%= simple_form_for @link do |f| %>
    <%= f.input :url %>
    <%= f.input :title %>
    <%= f.button :submit %>
<% end %>

app/views/links/show.html.erb
<%= @link.url %>
<%= @link.title %>

app/views/pages/index.html.erb
<h2>Homepage</h2>
<p> <%= link_to 'Create Link', new_link_path %></p>

<%= simple_form_for Link.new do |f| %>
    <%= f.input :url %>
    <%= f.input :title %>
    <%= f.button :submit %>
<% end %>

<ul>
    <% @links.each do |link| %>
    <li>
        <%= link_to "#{link.title}", "#{link.url}" %>
    </li>
    <li>
        <%= link_to 'Show more info', link_path(link) %>
    </li>
    <% end %>
</ul>